### ISSUE TITLE
Ligand parameterization panda code error

### ISSUE THREAD

**Issue by yuuhi1341** [pablo-arantes/making-it-rain#103]
![Screenshot (100)](https://github.com/pablo-arantes/making-it-rain/assets/162940821/31e41247-eb77-47cb-bf36-e28a034b2b81)

**Comment by patjiang** [comment]
@yuuhi1341 Hello! I've also encountered this issue many times, myself. It seems asthough the issue is more endemic to rdkit, rather than making-it-rain.

https://github.com/rdkit/rdkit/issues/7159

This issue has only come up in recent versions of both rdkit and pandas, as the notebook has worked for me in the past. I would suggest downloading older versions of both, and then seeing if the issue resolves itself

Best wishes,
Patrick Jiang

**Comment by pablo-arantes** [comment]
Hi All,

Sorry for the delay. I've fixed the notebook, I just tried here and everything went well for me.

Thank you.

Best,

Pablo
