### ISSUE TITLE
Problems concatenating trajectory

### ISSUE THREAD

**Issue by alessandronascimento** [pablo-arantes/making-it-rain#18]
Hi Make-it-rain guys,

First of all, thanks for this awesome tool! I loved the idea!

I'm running a simulation using AMBER input, which I generated before using leap.

Everything was ok in the colab up to the point where I am trying to concatenate the trajectories.  In this step, I have the following error message:

**************************************************************************************************

IndexError                                Traceback (most recent call last)

[<ipython-input-12-e0ce25ec2a43>](https://localhost:8080/#) in <module>()
     20 
     21 trajlist = pt.load(flist, pdb, stride=stride_traj)
---> 22 traj_image = trajlist.iterframe(autoimage=True, rmsfit=0)
     23 traj_write = pt.write_traj(traj_end, traj_image, overwrite=True)
     24 traj_load = pt.load(traj_end, pdb)

1 frames

[/usr/local/lib/python3.7/site-packages/pytraj/trajectory/trajectory.py](https://localhost:8080/#) in __getitem__(self, index)
    303         """
    304         if self.n_frames == 0:
--> 305             raise IndexError("Your Trajectory is empty, how can I index it?")
    306 
    307         if is_int(index):

IndexError: Your Trajectory is empty, how can I index it?

**************************************************************************************************

It does not seem to be system dependent, since I tries two different systems already with the same issue. Any ideas of what might be going on here?

Thanks.

**Comment by pablo-arantes** [comment]
Hi @alessandronascimento,

Thank you so much for your feedback. We are very glad to see people using Making it Rain.
Regarding your issue, I tried here and everything worked fine for me. I was able to concatenate the trajectory on Amber_inputs notebook.
I have one point to make, if your notebook disconnected, you should run again the cells with the same parameters (from the beginning). The code will recognize your files, and it will not run again the production step. Please, remember to use the same parameters, as Stride_time, Number_of_stried and so on. This is necessary because some variables are declared in the previous cells in the notebook.

Please, let me know if it is working.

Thank you.

Best,

Pablo

**Comment by pablo-arantes** [comment]
Hi @alessandronascimento,

De nada... ;-)

Thank you so much for your feedback and your suggestion. For sure, we will try to implement that.

All the best,

Pablo
