### ISSUE TITLE
Possiblity to append/continue simuations;

### ISSUE THREAD

**Issue by Arikite-netizen** [pablo-arantes/making-it-rain#24]
Respected Sir,
I came across your Google Colab Notebook (& whitepaper) while searching for cloud based computation  for protein ligand simulations. i was kind of impressed by the way you have assembled the entire toolset that would be require for peforming simulations. However , while trying it for my personal research ,it stated that a 100ns simulation for the protein ligand  simulation would take about 2 days. this would be quite difficult as maximus google colab offers to me is 6-12 hours of runtime. thus, i wanted to break the simulation in parts and append it time to time. But couldn't find any feature associated which could allow me to continue the simulation from the checkpoint. Thus, could you please help if you know how to continue simulation from where it is halted

**Comment by pablo-arantes** [comment]
Hi @Arikite-netizen,

Thank you so much for your feedback. We are very glad to see people using Making it Rain.
Regarding your issue, if your notebook disconnected, you should run again the cells with the **same parameters** (from the beginning). The code will recognize your files, and it will continue the simulation from the checkpoint on production step. 
That was the reason we have been using strides, the user can calculate how many nanoseconds per day and then select the number of strides and simulation time for 12 hours of run (free) or 24 hours (pro) on Google Colab. I understand that sometimes Google force to stop and unfortunately, we should run the last step from the beginning. My suggestion is to create a higher number of strides with a shorter simulation time. Thereby, if you lose your last stride because of Google interruptions, it will be fast to run again.
Please, remember to use the **same parameters**, as Stride_time, Number_of_stried and so on. This is necessary because some variables are declared in the previous cells in the notebook.

Please, let me know if it is working.

Thank you.

Best,

Pablo

**Comment by Arikite-netizen** [comment]
Thank you for the reply. It would be really helpful. However, do we need to prepare backup of those files so that the program can run ahead of where it had to halt

**Comment by pablo-arantes** [comment]
Hi @Arikite-netizen,

Sorry for my delay.
I don't know if I understood your point here. Yes, you should have your  previous run files in your Google Drive folder. Then, you can continue your simulations where it stopped. As I said above, "_The code will recognize your files, and it will continue the simulation from the checkpoint on production step."_ 

Please let me know if you have any question.

I'm closing the issue for now.

Best,

Pablo
