### ISSUE TITLE
Small problems running the script and information

### ISSUE THREAD

**Issue by ggoetten** [pablo-arantes/Making-it-rain#3]
Hi @pablo-arantes 

I have some very noob questions but I thought in adding it here as other users may have the same problem.

So on the production protocol in order for us to be able to continue our simulation, after GPU from google has been withdrawn, it is a good idea to set up a higher number of "Number_of_strides" so as the strides being performed are then saved in, supposed, the default file 1aki_equil.rst . My problem is that if we start this step again (after the 9 h stop cycle forced by google), colab rerun's it from the beginning and I loose what has been achieved before (like 5% of the run). Should we do something in the config file in order for google detect that we actually have some data already calculated?

Another problem that I have is that if I close the web browser and come back to the same notebook after google dcd me, I have to run the environment again (installation of py3Dmol etc...) is this normal?

Finally, I am getting 16 ns/day from colab with GPU (~200K atoms using the CHARMM script) I can see from your manuscript that this value should be a little higher (I understand that this has nothing to do with your software and rather with google freeware version) but do you have any tip about how to improve this?

Thank you very much for this wonderful python script, I was running my simulation with NAMD2 but it takes a lot of time and was almost giving up. Your code really helps a lot.

Regards.

**Comment by pablo-arantes** [comment]
Hi @ggoetten 

Thank you for your message! I'm glad our pipeline is helping you. Our main goal when we started to develop it was to give computational power for everyone (Make it rain!)... :-)

Regarding your questions, follow the answers:

1) Unfortunately, it is not possible to continue this last step where it has stopped. That was the reason we have been using strides, the user can calculate how many nanoseconds per day and then select the number of strides and simulation time for 12 hours of run (free) or 24 hours (pro). I understand that sometimes Google force to stop and unfortunately, we should run the last step from the beginning. My suggestion is to create a higher number of strides with a shorter simulation time. Thereby, if you lose your last stride because of Google interruptions, it will be fast to run again.

2) Yes, you should run the installation of dependencies every time you log in Colab. When you connect a GPU from Google, you are creating a virtual machine. So, every time you need to install the dependencies again. At least, the installation takes no more than 7 minutes. This is very common on Colab, if you are going to run a different script for example, with machine learning stuffs, you should install the libraries every time you connect too.

3) Our benchmark was made with Amber force field, not only that, depends on the size of the box. Maybe you are using a bigger box than us, with more waters and so on. 

I hope it helps.

Let me know if you have more questions.

Best,

Pablo

**Comment by ggoetten** [comment]
Hi @pablo-arantes

Thank you for the answers, I just noticed that the way the python script is handled, google colab starts on the correct stride after a crash or a disconnect. Very nice!

Thank you again!

Regards.
