### ISSUE TITLE
How to Deal Metallo-proteins with an Organic Molecule as a Ligand?

### ISSUE THREAD

**Issue by Ash1000** [pablo-arantes/making-it-rain#34]
Hello, I came to know that GAFF failed to parameterize the metal ions, as a result, the organic molecule (ligand) jumped out of the pocket. On closer inspection of the test run, where I tried both GAFF and OpenFF, both have removed the metal ions (Zn in my case). Would please guide, if there is any other way of handling it, using these notebooks?

**Comment by pablo-arantes** [comment]
Hi @Ash1000,

Sorry for my delay.
Unfortunately, our notebook does not accept metal ions. We need to change the code to accept this type of proteins. We are working on that, I will let you know when it's ready.

Thank you. 

Best, 

Pablo.

P.S: I will close the other issue regarding the volume, I suppose the issue was the ligand PDB. Right?
