### ISSUE TITLE
Equilibration MD simulation Error

### ISSUE THREAD

**Issue by dimkorov** [pablo-arantes/making-it-rain#49]
Hello,

Firstly, thanks a lot for making-it-rain, amazing!

I want to run a simulation with my protein using CHARMM but I am getting an error at the "_Runs an Equilibration MD simulation (NPT ensemble)_" step (see copied error attached). Everything before that  works fine. As this protein was embedded in a bilayer, I thought that was the issue. But then, when I repeated the steps using 1AKI (the protein you used in the example) but with **files I generated using solution builder** in CHARMM_GUI, it also stopped at the same step. I guess it has to do with topology or something but can't figure out (I'm no expert in MD or coding). Could you please let me know how to circumvent it?

Thanks a lot in advance.

Best,
Dimitris

[Error.txt](https://github.com/pablo-arantes/making-it-rain/files/10243894/Error.txt)

**Comment by dimkorov** [comment]
**Update**: It seems it's working now, even thought I didn't change anything so please ignore my previous message. Could you please however advice me on values for "Minimization_steps", "Simulation time", and "Position restraints force constant" for a protein embedded in membrane for the equilibration step?

Thanks again.

Best,
Dimitris

**Comment by zhenwilliam** [comment]
I came across an error entitled "AttributeError: XX object has no attribute XX" at this cell "Equilibration MD simulation". I don't know what happened.

**Comment by mdpoleto** [comment]
@dimkorov generally, we don't provide suggestions on the best parameters to setup a simulation since they are very case-dependent and have little to no information at all to make any decisions. Please refer to papers in the field simulating proteins in membranes.

But let me remind you that these notebooks ARE NOT suited for membrane simulations since we have opted for a isotropic barostat. If you want to use them for membranes, please refer to [the openmm membrane barostat page](http://docs.openmm.org/development/api-python/generated/openmm.openmm.MonteCarloMembraneBarostat.html) and modify the notebook accordingly.
