### ISSUE TITLE
Error while incorporating metal atoms in protein MD

### ISSUE THREAD

**Issue by 1heman** [pablo-arantes/making-it-rain#5]
I found the notebook to be working incredibly well for protein-ligand simulation when the ligand was an organic molecule.

Here is what I had done before I came across an error. I tried to simulate an APO protein with just Zn atoms. My input files were the protein.pdb and a pdb file containing just the Zn atoms (ligand.pdb). I was getting the following error in the _parametrization_ step.

```
cat: /content/drive/MyDrive/Source/ligand_gaff.pdb: No such file or directory
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-b8ef11d5d9db> in <module>()
    158         vol = float(line.split()[1])
    159 
--> 160 vol_lit  = vol * pow(10, -27)
    161 atom_lit = 9.03 * pow(10, 22)
    162 conc = float(Concentration)

NameError: name 'vol' is not defined

```

The `line` in line #158 is being read from a temporary copy of a part of **leap.log** file that contains 'Volume:'. However, this word 'Volume:' is not present in **leap.log** file.

Any help would be greatly appreciated. 
Hemant

**Comment by mdpoleto** [comment]
Generally, Zn (or any other ions) should not be treated as ligands. Metal ions are very tricky to be parametrized - and Zn is not an exception - reason why they undergo extensive calibration efforts and validation studies. Antechamber generates ligand parameters using GAFF, which is not suitable for Zn (or any other metal ions). In fact, Antechamber fails this task, which is why you are getting an error.

 If your Zn is a cofactor, it should be listed as an atom/hetatm entry in your protein.pdb and assigned with official Amber parameters. Thus, you should be using our first notebook (https://colab.research.google.com/github/pablo-arantes/Making-it-rain/blob/main/Amber.ipynb) or our fifth (https://colab.research.google.com/github/pablo-arantes/making-it-rain/blob/main/Amber_inputs.ipynb)

**Comment by 1heman** [comment]
Hi @mdpoleto 

I did follow your advice. I combined the Zn atoms with my protein and used (https://colab.research.google.com/github/pablo-arantes/making-it-rain/blob/main/Amber_inputs.ipynb) notebook. The outcome of this was that the Zn atoms were not being recognized. The result was same whether I labelled the Zn as HETATM or ATOM.

I have not tried the other notebook where we need to feed the **crd** and **prmtop** files along with the **pdb** file.

**Comment by pablo-arantes** [comment]
Hi @1heman,

Thank you for your inputs. 
I'm checking the code and I will let you know when it's done. 

Thank you.

Best,

Pablo

**Comment by 1heman** [comment]
Hi @pablo-arantes 

I came across a resource which talks about modelling Zn ions in Amber MD.
Here's the link to that: [ZAFF](https://ambermd.org/tutorials/advanced/tutorial20/ZAFF.htm)

I adopted the ZAFF.prep and ZAFF.frcmod from the above resource and incorporated them in the Amber.ipynb notebook. I uploaded these files both in the Colab memory as well as in my drive since I didn't know where exactly to put them. 

Made the following additions in the _parametrization step_.(changes within [])
```
f = open(tleap, "w")
f.write("""source """ + str(ff) + "\n"
"""source leaprc.DNA.OL15
source leaprc.RNA.OL3
source leaprc.GLYCAM_06j-1 
source leaprc.lipid17
source leaprc.gaff2
[loadamberprep ZAFF.prep 
loadamberparams ZAFF.frcmod]
```
This at least kept me away from the error I started the issue with. However, the problem was that 

1. the Zn ions were not featuring in my simulation
2. the Cys and His making up the Zn-fingers were not featuring in my simulation box.

That's where I've reached till now.

Thank you
-Hemant

**Comment by mdpoleto** [comment]
@1heman 

You are describing an Amber problem, and not a problem in our notebooks. Note that ZAFF models your system differently than regular FFs. You have to define your coordination center, the residues involved in coordination, etc. It is not a "plug-and-play" kind of approach, like biomolecules. I strongly advise you to make that model locally using the Amber package instead of trying to automate it here. 

Once you have your system built and are 100% sure it is correct, then use our notebook 5 to upload the respective .crd, .prmtop and .pdb files and they should work just fine.

**Comment by 1heman** [comment]
@mdpoleto 

Thank you for your inputs. I shall do that.

Now, if there is a system with Mg ions along with ligands, will I need to again model it separately, generate the necessary .crd, .prmtop and .pdb files and then use them in your notebook 5? 

If so, then in what all cases (other than MD of APO structures and simple protein-ligand complexes) can this _plug and play_ approach be applied using your notebooks?

**Comment by mdpoleto** [comment]
@1heman 

In principle, any system can be considered plug and play if one understands how tleap will handle the particles in their system based on a given force field... In practice, most simple ions (Mg2+, K+, Na+, Ca2+ and Cl- ) are available within the Amber protein force fields and, therefore, would be handled by tleap with no issues in notebook 1.

Your case is not simple, as I mentioned. Zn coordination is a historically difficult task in all additive force field families, requiring manual adjustments and definitions (like ZAFF, for instance). We made notebooks 2 and 5 specifically for "not plug and play" cases like yours (or protein in membranes, or organic liquids boxes, or systems with different force field files).

Anyway, if you think it is possible to modify the notebooks to create one capable of handling Zn-coordinating systems, please provide a minimal working example and we can evaluate the possibility of including it in our notebook repository.

**Comment by 1heman** [comment]
Thank you for your response, @mdpoleto 

I will surely let you know if I succeed in tinkering with your notebooks to make them capable of handling Zn-coordinate systems. 
Your notebooks surely have taught me a lot and I'm very grateful for that.
