### ISSUE TITLE
protein_ligand topology builder (vol is not defined)

### ISSUE THREAD

**Issue by imeldp96** [pablo-arantes/making-it-rain#67]
it gives error like this

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-7-c62522eec386>](https://localhost:8080/#) in <cell line: 159>()
    157         vol = float(line.split()[1])
    158 
--> 159 vol_lit  = vol * pow(10, -27)
    160 atom_lit = 9.03 * pow(10, 22)
    161 conc = float(Concentration)

NameError: name 'vol' is not defined

**Comment by pablo-arantes** [comment]
Hi @imeldp96,

This issue is on topology generation. The tleap is not able to create your topology for your protein/ligand structure.
Can you please double-check your ligand PDB file? Please, compare with examples PDB that we have here in GitHub (https://github.com/pablo-arantes/making-it-rain/tree/main/PROTEIN_LIGAND) for the protein ligand notebook.

I hope it helps.

Thank you.

Best,

Pablo
