### ISSUE TITLE
Error on "Parameters to generate the molecule topology on GAFF2 force field:"

### ISSUE THREAD

**Issue by chemuser168** [pablo-arantes/making-it-rain#70]
I am using the program on Google collab and I keep getting an error when I get to the "Parameters to generate the molecule topology on GAFF2 force field:" cell.

It says:

NameError                                 Traceback (most recent call last)

[<ipython-input-16-7abd7e2bf3a8>](https://localhost:8080/#) in <cell line: 157>()
    155         vol = float(line.split()[1])
    156 
--> 157 vol_lit  = vol * pow(10, -27)
    158 atom_lit = 9.03 * pow(10, 22)
    159 conc = float(Concentration)

NameError: name 'vol' is not defined

**Comment by pablo-arantes** [comment]
Hi @chemuser168,

This issue is on topology generation. The tleap is not able to create your topology for your protein/ligand structure.
Can you please double-check your ligand PDB file? Please, compare with examples PDB that we have here in [GitHub](https://github.com/pablo-arantes/making-it-rain/tree/main/PROTEIN_LIGAND) for the protein ligand notebook.

I hope it helps.

Thank you.

Best,

Pablo
