### ISSUE TITLE
Can't run protein-nanoparticle simulation.

### ISSUE THREAD

**Issue by noumanistic** [pablo-arantes/making-it-rain#99]
can you help  me how can i run protein-nanoparticle simulation.
i am using https://colab.research.google.com/github/pablo-arantes/making-it-rain/blob/main/Protein_ligand.ipynb
but it makes error at generating topology.
NameError                                 Traceback (most recent call last)
[<ipython-input-21-34da243fa244>](https://localhost:8080/#) in <cell line: 159>()
    157         vol = float(line.split()[1])
    158 
--> 159 vol_lit  = vol * pow(10, 27)
    160 atom_lit = 9.03 * pow(10, -22)
    161 conc = float(Concentration)

NameError: name 'vol' is not defined

**Comment by pablo-arantes** [comment]
Hi @noumanistic,

Unfortunately this notebook was developed to run protein+ligand systems, I don't think it will work for nanoparticle. That is the reason you're having issue in the topology generation cell, somehow Amber is not recognizing your nanoparticle (probably due to the missing parameters). 
My suggestion is change the code for your specific case and try it again. 

Thank you.

Best,

Pablo
